#!/usr/bin/env python3
"""
Generate standalone files — called by standalone.yml workflow.
Zero-hardcode design: clean → generate → manifest.
"""
import os
import re
from pathlib import Path

SRC = os.environ.get("PATCHER_SRC", "src/nonebot_plugin_parser_lite")
SRC_PREFIX = SRC
_MANIFEST = ".standalone-generated"
GENERATED_FILES: list[str] = []


def _clean_generated():
    """Delete all files and directories listed in the manifest from last run."""
    manifest = Path(_MANIFEST)
    if not manifest.exists():
        return
    # Never delete these — real source files that the generator patches in-place
    _PROTECTED = {
        "src/nonebot_plugin_parser_lite/__init__.py",
        "src/nonebot_plugin_parser_lite/utils/cookie.py",
    }
    removed = 0
    for line in manifest.read_text("utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.rstrip("/") in _PROTECTED:
            continue
        path = Path(line)
        if path.is_dir() and line.endswith("/"):
            import shutil
            shutil.rmtree(path, ignore_errors=True)
            removed += 1
        elif path.exists():
            path.unlink()
            removed += 1
    manifest.unlink(missing_ok=True)
    if removed:
        print(f"  cleaned {removed} generated entries")


_clean_generated()
os.makedirs(f"{SRC}/utils", exist_ok=True)


def _write(path: str, content: str):
    full = os.path.join(SRC, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)
    GENERATED_FILES.append(f"{SRC_PREFIX}/{path}")
    print(f"  {path}")

# ── env.py ──
_write("utils/env.py",
    'import os\n\n'
    'IS_STANDALONE = os.environ.get("PARSER_LITE_STANDALONE") == "1"\n')

# ── _flags.py ──
_write("utils/_flags.py",
    'import os\n\n'
    '_IS_STANDALONE = os.environ.get("PARSER_LITE_STANDALONE", "") == "1"\n'
    'PARSER_LITE_STANDALONE = _IS_STANDALONE\n'
    'PARSER_LITE_PRE = "plite_"\n'
    'if _IS_STANDALONE:\n'
    '    _STANDALONE = True\n'
    '\n'
    '    def _get_flag(flag: str) -> str:\n'
    '        return os.environ.get(f"{PARSER_LITE_PRE}{flag}", "")\n'
    'else:\n'
    '    from nonebot import get_driver\n'
    '\n'
    '    _STANDALONE = False\n'
    '\n'
    '    def _get_flag(flag: str) -> str:\n'
    '        return getattr(get_driver().config, f"{PARSER_LITE_PRE}{flag}", "")\n')

# ── _standalone_fake.py ──
stubs, seen = [], set()
submods: set[str] = set()  # e.g. {"nonebot.log", "nonebot.adapters"}
plugin_mods: set[str] = set()  # e.g. {"nonebot_plugin_htmlrender", "nonebot_plugin_alconna.uniseg"}
for root, dirs, files in os.walk(SRC):
    for fn in files:
        if not fn.endswith(".py") or fn in ("_flags.py", "env.py", "_standalone_fake.py"):
            continue
        in_paren = False
        with open(os.path.join(root, fn), encoding="utf-8") as _f:
            _text = _f.read()
        for line in _text.split("\n"):
            m = re.match(r"from\s+(nonebot(\.[a-z_]+)?)\s+import\s+(.+?)(?:\s*#.*)?$", line)
            pm = re.match(r"from\s+(nonebot_plugin_[a-z_]+(?:\.[a-z_]+)*)\s+import\s+(.+?)(?:\s*#.*)?$", line)
            if m:
                path = m.group(1)  # e.g. "nonebot.log" or "nonebot"
                if "." in path:
                    submods.add(path)
                raw = m.group(3).strip()
                if raw.endswith("("): in_paren = True; raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n); stubs.append(n)
            elif pm:
                plugin_mods.add(pm.group(1))
                raw = pm.group(2).strip()
                if raw.endswith("("): in_paren = True; raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n); stubs.append(n)
            elif in_paren:
                raw = line.split("#")[0].strip()
                if raw.endswith(")"): in_paren = False; raw = raw[:-1]
                if raw.endswith(","): raw = raw[:-1]
                for n in raw.split(","):
                    n = n.strip().split(" as ")[0]
                    if n and n not in seen:
                        seen.add(n); stubs.append(n)

stub_content = "# Auto-generated by standalone workflow. Do not edit.\n"
stub_content += "\n".join(f"{s} = None  # type: ignore" for s in sorted(stubs)) + "\n"
_write("utils/_standalone_fake.py", stub_content)
print(f"  ({len(stubs)} stubs: {', '.join(sorted(stubs))})")

# ── nonebot stub package ──
# Upstream files do `from nonebot import ...` which fails if nonebot is not installed.
# This stub package provides recursive mocks so all imports and calls succeed silently.
_SRC_DIR = os.path.dirname(SRC)  # src/
_nb_dir = os.path.join(_SRC_DIR, "nonebot")
os.makedirs(_nb_dir, exist_ok=True)
_nb_init = os.path.join(_nb_dir, "__init__.py")
_nb_stub = '''# Auto-generated standalone stub for nonebot
class _NonebotMock:
    """Recursive mock: attribute → self, call → self, iter → [self], falsy."""
    def __getattr__(self, name):
        return self
    def __call__(self, *args, **kwargs):
        return self
    def __iter__(self):
        return iter([self])
    def __bool__(self):
        return False
    def __len__(self):
        return 0
    def __repr__(self):
        return "nonebot-mock"
    def __contains__(self, item):
        return True

_m = _NonebotMock()
'''
for s in sorted(stubs):
    if s == "get_plugin_config":
        continue  # defined manually below as a real function
    _nb_stub += f'{s} = _m\n'

# get_plugin_config override: return a real Config instance using defaults
# so that pconfig.zhihu_ck is None (falsy) instead of a truthy mock
_nb_stub += '''
def get_plugin_config(config_cls):
    """Standalone: instantiate the config class with defaults (no nonebot driver)."""
    try:
        return config_cls()
    except Exception:
        return _m

import logging
logger = logging.getLogger("parser-lite")
'''
# Submodule fallback: `from nonebot.adapters import X` calls __getattr__ on module
_nb_stub += '''
import sys as _sys

def __getattr__(name):
    sub = _NonebotMock()
    setattr(_sys.modules[__name__], name, sub)
    return sub
'''
with open(_nb_init, "w", encoding="utf-8") as f:
    f.write(_nb_stub)
GENERATED_FILES.append("src/nonebot/__init__.py")
print(f"  nonebot/__init__.py ({len(stubs)} stubs)")

# ── nonebot_plugin_localstore stub ──
_nls_dir = os.path.join(_SRC_DIR, "nonebot_plugin_localstore")
os.makedirs(_nls_dir, exist_ok=True)
_nls_init = os.path.join(_nls_dir, "__init__.py")
_nls_stub = '''# Auto-generated standalone stub for nonebot_plugin_localstore
from pathlib import Path as _Path

_base = _Path("data").resolve()
def get_plugin_cache_dir():
    return _base / "cache"
def get_plugin_config_dir():
    return _base / "config"
def get_plugin_data_dir():
    return _base / "data"
'''
with open(_nls_init, "w", encoding="utf-8") as f:
    f.write(_nls_stub)
GENERATED_FILES.append("src/nonebot_plugin_localstore/__init__.py")
print("  nonebot_plugin_localstore/__init__.py")

# ── nonebot submodule stubs ──
# `from nonebot.log import logger` requires actual nonebot/log/__init__.py stub,
# not just __getattr__ on the parent module.
for _sm in sorted(submods):
    _parts = _sm.split(".")
    _sm_dir = os.path.join(_SRC_DIR, *_parts)
    os.makedirs(_sm_dir, exist_ok=True)
    _sm_init = os.path.join(_sm_dir, "__init__.py")
    _sm_stub = f'''# Auto-generated standalone stub for {_sm}
class _NonebotMock:
    def __getattr__(self, name):
        return self
    def __call__(self, *args, **kwargs):
        return self
    def __iter__(self):
        return iter([self])
    def __bool__(self):
        return False
    def __repr__(self):
        return "nonebot-mock"
    def __contains__(self, item):
        return True

_m = _NonebotMock()
'''
    for s in sorted(stubs):
        _sm_stub += f'{s} = _m\n'
    _sm_stub += '''
import logging
logger = logging.getLogger("parser-lite")
'''
    with open(_sm_init, "w", encoding="utf-8") as f:
        f.write(_sm_stub)
    GENERATED_FILES.append("src/" + "/".join(_parts) + "/__init__.py")
    print(f"  {'/'.join(_parts)}/__init__.py")

# ── nonebot_plugin_* stub packages ──
# Upstream imports third-party nonebot plugins at module level
# (htmlrender/alconna/apscheduler/uninfo). Bridge only needs them importable;
# actual calls are handled by bridge's own implementations.
for _pm in sorted(plugin_mods):
    _parts = _pm.split(".")
    _pm_dir = os.path.join(_SRC_DIR, *_parts)
    os.makedirs(_pm_dir, exist_ok=True)
    _pm_init = os.path.join(_pm_dir, "__init__.py")
    _pm_stub = f'''# Auto-generated standalone stub for {_pm}
class _StubMeta(type):
    """Metaclass: class-level attribute access + isinstance always True."""
    def __getattr__(cls, name):
        return cls
    def __instancecheck__(cls, inst):
        return True

class _Stub(metaclass=_StubMeta):
    """Stub usable as type alias (X | Y), class (X(...)), and namespace."""
    def __init__(self, *args, **kwargs):
        pass
    def __getattr__(self, name):
        return self
    def __call__(self, *args, **kwargs):
        return self
    def __iter__(self):
        return iter(())
    def __bool__(self):
        return False
    def __repr__(self):
        return "nonebot-plugin-stub"
    def __contains__(self, item):
        return True
    def __or__(self, other):
        return other
    def __ror__(self, other):
        return self

'''
    for s in sorted(stubs):
        _pm_stub += f'{s} = _Stub\n'
    _pm_stub += '''
import logging
logger = logging.getLogger("parser-lite")
'''
    with open(_pm_init, "w", encoding="utf-8") as f:
        f.write(_pm_stub)
    GENERATED_FILES.append("src/" + "/".join(_parts) + "/__init__.py")
    print(f"  {'/'.join(_parts)}/__init__.py")

# ── __init__.py ──
init_path = f"{SRC}/__init__.py"
text = open(init_path, encoding="utf-8").read()
if "_STANDALONE" in text:
    print("  __init__.py already patched, skipping")
else:
    guard = (
        'from .utils._flags import _STANDALONE, _get_flag  # noqa: F401\n\n'
        'if _STANDALONE:\n'
        '    from .utils._standalone_fake import *  # noqa: F403\n'
        '    from logging import getLogger as _getLogger\n'
        '    logger = _getLogger("parser-lite")\n'
        '    try:\n'
        '        from apscheduler.schedulers.asyncio import AsyncIOScheduler\n'
        '        scheduler = AsyncIOScheduler()\n'
        '        scheduler.configure({"apscheduler.timezone": "Asia/Shanghai"})\n'
        '        try: scheduler.start()\n'
        '        except RuntimeError: pass\n'
        '    except ImportError:\n'
        '        scheduler = None\n'
        '    def clear_result_cache() -> None: pass\n'
        'else:\n'
    )
    indented = "\n".join("    " + line if line.strip() else "" for line in text.split("\n"))
    with open(init_path, "w", encoding="utf-8") as f:
        f.write(guard + indented)
    GENERATED_FILES.append(f"{SRC_PREFIX}/__init__.py")
    print("  __init__.py patched")

# ── ruff.toml ──
rt_path = "ruff.toml"
BRIDGE_IGNORES = ["E501", "E701", "E702", "ASYNC240", "RUF100", "E902", "T201"]
if os.path.exists(rt_path):
    with open(rt_path, encoding="utf-8") as f:
        full = f.read()
    if '  "E501"' not in full:
        full = full.replace(
            "ignore = [",
            "ignore = [\n  " + ", ".join(f'"{r}"' for r in BRIDGE_IGNORES) + ","
        )
    # Remove old per-file-ignores (if any), regenerate from scratch
    lines = full.split("\n")
    clean = []
    skip = False
    for line in lines:
        if line.startswith("[lint.per-file-ignores]"):
            skip = True
            continue
        if skip and line.startswith("["):
            skip = False
        if not skip:
            clean.append(line)
    full = "\n".join(clean).rstrip("\n") + "\n\n[lint.per-file-ignores]\n"
    full += f'"{SRC_PREFIX}/utils/_standalone_fake.py" = ["ALL"]\n'
    for gf in GENERATED_FILES:
        if gf != f"{SRC_PREFIX}/utils/_standalone_fake.py":
            full += f'"{gf}" = ["I001"]\n'
    # Scan all upstream Python files and add I001 ignores (they often have
    # unsorted imports due to conditional nonebot imports at module level)
    for root, dirs, files in os.walk(SRC):
        for fn in files:
            if not fn.endswith(".py"):
                continue
            rel = os.path.relpath(os.path.join(root, fn)).replace("\\", "/")
            if any(rel.startswith(gf.replace("\\", "/")) for gf in GENERATED_FILES):
                continue
            full += f'"{rel}" = ["I001"]\n'
    with open(rt_path, "w", encoding="utf-8") as f:
        f.write(full)
    print(f"  ruff.toml injected ({len(GENERATED_FILES)} files)")

# ── Strip NoneBot deps + remove version upper bounds ──
req_path = "requirements.txt"

# ── Hardening: patch ck2dict to handle malformed cookies ──
_ck_path = os.path.join(SRC, "utils", "cookie.py")
if os.path.exists(_ck_path):
    with open(_ck_path, encoding="utf-8") as f:
        _ck_text = f.read()
    if "split_result" not in _ck_text:
        _ck_text = _ck_text.replace(
            'name, value = cookie.strip().split("=", 1)',
            'split_result = cookie.strip().split("=", 1)\n'
            '        name, value = split_result if len(split_result) > 1 else (split_result[0], "")'
        )
        with open(_ck_path, "w", encoding="utf-8") as f:
            f.write(_ck_text)
        print("  utils/cookie.py: ck2dict hardened")
if os.path.exists(req_path):
    with open(req_path, encoding="utf-8") as f:
        req_lines = f.readlines()
    clean = []
    for ln in req_lines:
        stripped = ln.strip()
        if not stripped or stripped.startswith("#"):
            clean.append(ln)
            continue
        if "nonebot" in stripped.lower():
            continue
        # Remove version upper bound (keep only lower bound)
        pkg_name = re.split(r"[<>=!~]", stripped)[0].strip()
        lower = re.search(r"(>=?[^,;\s]+)", stripped)
        if lower:
            clean.append(f"{pkg_name}{lower.group(1)}\n")
        else:
            clean.append(f"{pkg_name}\n")
    if len(clean) != len(req_lines):
        with open(req_path, "w", encoding="utf-8") as f:
            f.writelines(clean)
        print(f"  requirements.txt: stripped {len(req_lines) - len(clean)} entries")

# ── Manifest: .standalone-generated ──
_mf_lines = []
# Generated directories: nonebot/ + submodules + nonebot_plugin_* + nonebot_plugin_localstore
_nb_sm_dirs = {f"src/{d.replace('.', '/')}" for d in submods}
_nb_sm_dirs.add("src/nonebot")
_nb_sm_dirs.add("src/nonebot_plugin_localstore")
for _pm in plugin_mods:
    _nb_sm_dirs.add("src/" + _pm.replace(".", "/"))
for d in sorted(_nb_sm_dirs):
    _mf_lines.append(d + "/")
# Generated files (from _write) — exclude in-place patched source files
for gf in sorted(GENERATED_FILES):
    _gf = gf.replace("\\", "/")
    if _gf.endswith("__init__.py") and not _gf.startswith("src/nonebot"):
        continue  # __init__.py is a source file patched in-place — never delete
    _mf_lines.append(_gf)
_mf_lines.append(_MANIFEST.replace("\\", "/"))
_mf_content = (
    "# Auto-generated files — do not edit manually.\n"
    "# Each line is a path relative to repo root (forward slashes).\n"
    "# Directories end with /.  Delete these entries to trigger a clean regeneration.\n"
    + "\n".join(_mf_lines) + "\n"
)
Path(_MANIFEST).write_text(_mf_content, "utf-8")
print(f"  {_MANIFEST} ({len(_mf_lines)} entries)")
